const SET_PERSIST_DATA = "SET_PERSIST_DATA";
const RESET_PERSIST_DATA = "RESET_PERSIST_DATA";
const SET_USERS = "SET_USERS";
const SET_REPOSITORIES = "SET_REPOSITORIES";
const RESET_PARAMS = "RESET_PARAMS";

export {
  SET_PERSIST_DATA,
  RESET_PERSIST_DATA,
  SET_USERS,
  SET_REPOSITORIES,
  RESET_PARAMS,
};
